### ISSUE TITLE
Parser options and some other things need updating

### ISSUE THREAD

**Issue by justinwoo** [gcanti/purescript-prettier#2]
https://github.com/gcanti/purescript-prettier/blob/4d89c3eec0cb39216b8d8b25af99b06ba70d68b8/src/Text/Prettier.purs#L65-L701

Mostly reminder to self, unless you want to do this. I just need CSS formatting.

It'd be nice if the formatImpl was also exposed for use

**Comment by gcanti** [comment]
Released
